### ISSUE TITLE
Many pad ops added to the conv 

### ISSUE THREAD

**Issue by liyancas** [PINTO0309/openvino2tensorflow#113]
### Issue Type

Performance

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO

### Download URL for ONNX / OpenVINO IR

refer to https://github.com/PINTO0309/openvino2tensorflow/issues/112

### Convert Script

refer to https://github.com/PINTO0309/openvino2tensorflow/issues/112

### Description

<img width="385" alt="图片" src="https://user-images.githubusercontent.com/6994414/177519084-e3a93d31-b1d0-4d1a-993f-71c57f4fba2e.png">

### Relevant Log Output

```shell
refer to https://github.com/PINTO0309/openvino2tensorflow/issues/112
```

**Comment by PINTO0309** [comment]
Pad reduction cannot be addressed. There is no exact specification match between OpenVINO and TensorFlow.
Have you checked to see if the layers of Padding are really affecting performance?

This is an unfixable condition. If you are dissatisfied with the tool's specifications, use onnx-tf.
