### ISSUE TITLE
xception65をkeras(h5)に変換したい

### ISSUE THREAD

**Issue by tatusya-suda** [PINTO0309/openvino2tensorflow#124]
### Issue Type

Others

### OS

Windows

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlow

### Download URL for ONNX / OpenVINO IR

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md

### Convert Script

!source /opt/intel/openvino_2021/bin/setupvars.sh && pb_to_saved_model \
--pb_file_path frozen_inference_graph.pb \
--inputs sub_2:0 \
--outputs ResizeBilinear_2:0

!source /opt/intel/openvino_2021/bin/setupvars.sh &&\
   python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
   --saved_model_dir saved_model_from_pb/ --output_dir model_saved --data_type FP32 

### Description

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md
のxception65_coco_voc_trainaug(.pb)をkeras(h5)に変換したいです。
しかし、openvino2tensorflowを使用して変換するときにpickleエラーが起きます。

環境はpython=3.8,tensorflow=2.5です。

変換ルートはpbからsaved_modelに変換したあと、IR形式に変換しています。

### Relevant Log Output

```shell
TypeError: can't pickle module objects
```

**Comment by PINTO0309** [comment]
1. Please let me know why you want to convert to `.h5`. This is a deprecated format at this time. `saved_model` should be sufficient for your needs.
2. Is this the model you are converting to? [deeplabv3_pascal_train_aug_2018_01_04.tar.gz](http://download.tensorflow.org/models/deeplabv3_pascal_train_aug_2018_01_04.tar.gz)
  ![image](https://user-images.githubusercontent.com/33194443/187063286-9d65cbe5-a526-44a6-848d-27e13b118f1d.png)
3. Your specification of the name of the input/output layer in your .pb is incorrect.
    ```bash
    pb_to_saved_model \
    --pb_file_path frozen_inference_graph.pb \
    --inputs ImageTensor:0 \
    --outputs SemanticPredictions:0
    ```
    ![image](https://user-images.githubusercontent.com/33194443/187063188-5a558940-4dfc-4db8-aa0a-253f47cae997.png)


```bash
saved_model_to_tflite \
--saved_model_dir_path saved_model_from_pb \
--input_shape [1,513,513,3] \
--model_output_dir_path saved_model \
--output_no_quant_float32_tflite
```
![image](https://user-images.githubusercontent.com/33194443/187064967-535c745e-faf9-48b1-8360-0c686204f97a.png)
```bash
cp saved_model/model_float32.tflite .

tflite2tensorflow \
--model_path model_float32.tflite \
--flatc_path ../flatc \
--schema_path ../schema.fbs \
--output_pb \
--optimizing_for_openvino_and_myriad
```
![image](https://user-images.githubusercontent.com/33194443/187066078-e961b03b-b6a9-4226-9d75-4a301816a596.png)
```bash
saved_model_cli show --dir saved_model --all

saved_model_cli show --dir saved_model --all
2022-08-28 08:57:19.305342: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['ImageTensor'] tensor_info:
        dtype: DT_UINT8
        shape: (1, 513, 513, 3)
        name: ImageTensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['SemanticPredictions'] tensor_info:
        dtype: DT_INT64
        shape: (1, 513, 513)
        name: SemanticPredictions:0
  Method name is: tensorflow/serving/predict
```

**Comment by tatusya-suda** [comment]
1.keras modelに変換して、モデルの剪定を実施したいです。
  剪定したモデルをtfliteに変換し、Androidへの実装を目指しています。
https://www.tensorflow.org/model_optimization/guide/pruning/pruning_with_keras

2.モデルはご指定のモデルです。

3.調べたときsub2とResizeBilinearを指定した例があったのでそちらで変換していました。ありがとうございます

**Comment by PINTO0309** [comment]
If that is the case, then this question is not about `openvino2tensorflow`, but about how to use `TensorFlow`. 

First, delete all unnecessary garbage processing in the range shown below.

- export_model.py
https://github.com/tensorflow/models/blob/1587d2db03455264fdc09b246a1ee56b88616499/research/deeplab/export_model.py#L91-L111
- model structure
![image](https://user-images.githubusercontent.com/33194443/187071790-a8731803-176c-48f7-a12e-1a77028aded4.png)
- Reference
[TensorFlow2でのモデルファイルの保存と読み込み](https://qiita.com/sn6/items/f9773fb1917cfd4bd1d4)
