### ISSUE TITLE
whisper openvino to tflite(https://huggingface.co/zhuzilin/whisper-openvino-tiny.en/tree/main)

### ISSUE THREAD

**Issue by nyadla-sys** [PINTO0309/openvino2tensorflow#132]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO

### Download URL for ONNX / OpenVINO IR

https://huggingface.co/zhuzilin/whisper-openvino-tiny.en

### Convert Script

openvino2tensorflow   --model_path ~/whisper-openvino-tiny.en/encoder.xml   --output_saved_model   --output_pb   --output_weight_quant_tflite   --output_float16_quant_tflite   --output_no_quant_float32_tflite

### Description

Not able to convert  whispper openvino model to tflite model
https://huggingface.co/zhuzilin/whisper-openvino-tiny.en/encoder.xml

### Relevant Log Output

```shell
• name=None
ERROR: Please refer to 6-7 in the README first. https://github.com/PINTO0309/openvino2tensorflow
```

**Comment by PINTO0309** [comment]
Please refer to 6-7 in the README first. https://github.com/PINTO0309/openvino2tensorflow
