### ISSUE TITLE
ImportError: libinference_engine.so Openvino to Tensorflow

### ISSUE THREAD

**Issue by NaeemKhan333** [PINTO0309/openvino2tensorflow#16]
Thanks @PINTO0309 for help . I am running following command and getting the error

openvino2tensorflow --model_path openvino/320x320/FP32/u2net_320x320_opt.xml --model_output_path saved_model_320x320 --output_saved_model True

Traceback (most recent call last):
File "/home/user/.local/bin/openvino2tensorflow", line 66, in
from openvino.inference_engine import IECore
File "/home/naeem/.local/lib/python3.6/site-packages/openvino/inference_engine/init.py", line 1, in
from .ie_api import *
ImportError: libinference_engine.so: cannot open shared object file: No such file or directory

Can you guide me what I am doing wrong.Thanks

**Comment by PINTO0309** [comment]
After installing openvino, you can use
```console:
$ source /opt/intel/openvino_2021/bin/setupvars.sh
```

**Comment by NaeemKhan333** [comment]
@PINTO0309 Thank you very much for help . The above given command solve my error

```
source /home/user/intel/openvino_2021/bin/setupvars.sh
```
