### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by NaeemKhan333** [PINTO0309/openvino2tensorflow#19]
@PINTO0309 Thank you for response . I am trying to convert the u2net model to tensorflow Js. I am getting error while I run the following command

```
openvino2tensorflow --model_path openvino/320x320/FP32/u2net_320x320_opt.xml --model_output_path saved_model_320x320 --output_saved_model True

Segmentation fault (core dumped)

```
I am using python 3.8 and openvino2021 for the conversion of model.Thanks

**Comment by PINTO0309** [comment]
Follow the issue template to post your issue. Close once.
