### ISSUE TITLE
Gather got multiple indices

### ISSUE THREAD

**Issue by khursani8** [PINTO0309/openvino2tensorflow#2]
Currently the conversion work fine so far until at Gather operation
It received multiple indices based on the screenshot below which will trigger:
*** TypeError: only size-1 arrays can be converted to Python scalars

![Screenshot from 2020-10-24 11-12-36](https://user-images.githubusercontent.com/5404903/97065636-d92b7800-15e9-11eb-806e-425028d6c766.png)

I tried take a look at Netron but don't know what to do based on the graph
![Screenshot from 2020-10-24 11-06-45](https://user-images.githubusercontent.com/5404903/97065590-67532e80-15e9-11eb-802a-4da01453e169.png)

Thanks

**Comment by PINTO0309** [comment]
I'd like to use a sample model to debug it if possible. Can you provide an IR model (.bin/.xml)?

**Comment by khursani8** [comment]
Sure

[xml](https://drive.google.com/file/d/1-RaefmQfqdPjrexT5bWkUsxZ73hqqSV9/view?usp=sharing)
[bin](https://drive.google.com/file/d/1-IilNOY5zFQPrwk66lZIi2Q_FH_0jcba/view?usp=sharing)

**Comment by PINTO0309** [comment]
I just fixed the Gather and ShapeOf conversion bug. 3b4a7a0690eb47d3a478091b17b24b51c261e308
The following link is tflite after conversion.
- model_unknown0001_float32.tflite
**https://drive.google.com/file/d/1D9CfZd8OWRQo4ZE9nN2geKwkIQJfXmOG/view?usp=sharing**

**Comment by khursani8** [comment]
Wow, after using latest script I can convert without any error.
I will take a look at the tflite model you share

If you are ok with it, can you share how you approach solving the bug?
Thanks :)

**Comment by PINTO0309** [comment]
I was remiss in transposing indices from NCHW to NHWC. I also changed ShapeOf from tf.keras.backend.shape to tf.shape and fixed the return dtype to int64.
Also, ReduceProd and Subtract were added because they were unsupported layers.

**Comment by khursani8** [comment]
Ohhh, now the code change make sense
Thanks again
