### ISSUE TITLE
list index out of range while converting model

### ISSUE THREAD

**Issue by DionisioII** [PINTO0309/openvino2tensorflow#20]
#### 4. Version of TensorFlow 2.3.1, but tried also with 2.4.1
####5 python version 3.7
####6 openvino model to convert: https://download.01.org/opencv/2021/openvinotoolkit/2021.2/open_model_zoo/models_bin/3/gaze-estimation-adas-0002/FP32/

I get this error while trying conversion:

```
(py_3_7) D:\work\openvino2tensorflow\openvino2tensorflow-main\openvino2tensorflow>python openvino2tensorflow.py --model_path D:\Librerie\Openvino\openvino_2021.2.185\deployment_tools\open_model_zoo\models\download\intel\gaze-estimation-adas-0002\FP16\gaze-estimation-adas-0002.xml --model_output_path . --output_pb 1
[07mTensorFlow/Keras model building process starts[0m ======================================
D:\work\openvino2tensorflow\py_3_7\lib\site-packages\tensorflow\python\autograph\utils\testing.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "openvino2tensorflow.py", line 2204, in <module>
    main()
  File "openvino2tensorflow.py", line 2200, in main
    yolact, debug, debug_layer_number)
  File "openvino2tensorflow.py", line 305, in convert
    tf_layers_dict[layer_id] = Input(shape=(shape[2], shape[3], shape[1]), batch_size=shape[0], name=layer_name)
IndexError: list index out of range

```

**Comment by PINTO0309** [comment]
Added support for input values other than 4D tensor and fixed some bugs. If you update to the latest package, you will be able to convert correctly. **commit:** fc68f0e58c37bda624b5bf7161a42fc41a8d9cf7

**Comment by PINTO0309** [comment]
Converted Model
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/091_gaze-estimation-adas-0002**

**Comment by DionisioII** [comment]
thanks a lot man!

Do you have some paypal link for donation?. I would like to send a couple of bucks

**Comment by PINTO0309** [comment]
I don't want that. I'm just playing as a hobby.

**Comment by DionisioII** [comment]
Thanks anyway. I will be sponsoring you just for this very month.
I also hope you will be willing to accept some tasks in the future for money. We could make good use of a guy like you.

**Comment by PINTO0309** [comment]
Whoa! Unbelievable! Thank you so much. :smiley:
