### ISSUE TITLE
to .h5 conversion issues

### ISSUE THREAD

**Issue by AnriZ75** [PINTO0309/openvino2tensorflow#32]
#### 13. Issue Details

When I tried to convert the following models to .h5 model, I got the following errors:

face-detection-adas-0001.xml

https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/2/face-detection-adas-0001/FP32/

Error: The PriorBox layer is not yet implemented

-------------------------------------------

facial-landmarks-35-adas-0002.xml

https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/2/facial-landmarks-35-adas-0002/FP32/

Error: MemoryError

-------------------------------------------

**Comment by PINTO0309** [comment]
Output to h5 is deprecated. Try to output to .pb or saved_model.

- facial-landmarks-35-adas-0002.xml

```bash
$ openvino2tensorflow \
  --model_path openvino/facial-landmarks035-adas-0002/facial-landmarks-35-adas-0002.xml \
  --output_saved_model True \
  --output_pb True \
  --output_no_quant_float32_tflite True
```
![Screenshot 2021-02-23 22:23:27](https://user-images.githubusercontent.com/33194443/108849664-c5d6fa80-7625-11eb-95b4-4aaa6905fad8.png)
https://drive.google.com/file/d/1qXQBldITV1iN7-hygfTOL6hTka0mdRud/view?usp=sharing

**Comment by PINTO0309** [comment]
Closed due to lack of response.
