### ISSUE TITLE
error while quantization of keras model

### ISSUE THREAD

**Issue by adjagetia** [PINTO0309/openvino2tensorflow#34]

**Comment by adjagetia** [comment]
got ` tf__call() got an unexpected keyword argument 'y'` for tf.math.add layers 
` tf__call() got an unexpected keyword argument 'b'` for tf.linalg.matmul layers 
` tf__call() got an unexpected keyword argument 'axis'` for tf.math.reduce_mean layers
` tf__call() got an unexpected keyword argument 'shape'` for tf.reshape layers and so on..

**Comment by adjagetia** [comment]
[tensorflow model optimization PR](https://github.com/tensorflow/model-optimization/pull/646/commits/5d46adca5dbe1f48f5b78670ab820d3246f1a344)
this helped to overcome the above problem, but now it says 
`RuntimeError: Layer tf.math.add:<class 'tensorflow.python.keras.layers.core.TFOpLambda'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.`

**Comment by PINTO0309** [comment]
No description.
