### ISSUE TITLE
tensorflow conversion error

### ISSUE THREAD

**Issue by duantiantian** [PINTO0309/openvino2tensorflow#39]
#### 3. Version of TensorFlow e.g. v2.5.0tc
```python
openvino2tensorflow --model_path scrfd_500m_bnkps_shape320x320.xml --output_pb
```
####  Issue Details
ValueError: Depth of input (5) is not a multiple of input depth of filter (3) for '{{node tf.nn.conv2d/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](Placeholder, tf.nn.conv2d/Conv2D/filter)' with input shapes: [1,320,322,5], [16,3,3,3].

Can you give me some suggestions?

**Comment by PINTO0309** [comment]
What is this model? I have been given very little information, so there is no way to find out.

**Comment by duantiantian** [comment]
can use docker successfully. thank you so much!!!
