### ISSUE TITLE
openvino to tensorflow falis

### ISSUE THREAD

**Issue by ofeknesher2** [PINTO0309/openvino2tensorflow#4]
trying to convert a ir model create with 2019 r2 openvino toolkit version with this command:

openvino2tensorflow   --model_path=raftC.xml   --output_saved_model True   --output_pb True   --output_weight_quant_tflite True   --output_no_quant_float32_tflite True

output:
import: not authorized `os' @ error/constitute.c/WriteImage/1028.
import: not authorized `sys' @ error/constitute.c/WriteImage/1028.
import: not authorized `argparse' @ error/constitute.c/WriteImage/1028.
import: not authorized `struct' @ error/constitute.c/WriteImage/1028.
import: not authorized `np' @ error/constitute.c/WriteImage/1028.
import: not authorized `et' @ error/constitute.c/WriteImage/1028.
from: can't read /var/mail/openvino.inference_engine
import: not authorized `tf' @ error/constitute.c/WriteImage/1028.
from: can't read /var/mail/tensorflow.keras
from: can't read /var/mail/tensorflow.keras.layers
from: can't read /var/mail/tensorflow.keras.initializers
from: can't read /var/mail/tensorflow.keras.backend
from: can't read /var/mail/tensorflow.keras.activations
from: can't read /var/mail/tensorflow.python.framework.convert_to_constants
import: not authorized `np' @ error/constitute.c/WriteImage/1028.
import: not authorized `sys' @ error/constitute.c/WriteImage/1028.
import: not authorized `tfds' @ error/constitute.c/WriteImage/1028.
/home/user/miniconda3/bin/openvino2tensorflow: line 79: syntax error near unexpected token `('
/home/user/miniconda3/bin/openvino2tensorflow: line 79: `def convert(model,'

**Comment by PINTO0309** [comment]
Please update the program and try again. d7110b9f3dbf3b18a9c159979f6cffd48e0780f4 17700b34bb58625c23d36a786aed876def1e16c0
`pip install git+https://github.com/PINTO0309/openvino2tensorflow --upgrade`

**Comment by ofeknesher2** [comment]
after installing the tensorflow-datasets and updating the tqdm i know get this msg;
**The Input layer is not yet implemented.**

as i see in netron the input layer of my model is: Convolution

**Comment by PINTO0309** [comment]
Is this a model you converted from Caffe?
https://docs.openvinotoolkit.org/2019_R2/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html

If possible, try upgrading to OpenVINO 2021.1 and generating the IR again.

**Comment by ofeknesher2** [comment]
Nope, my model is from onnx.
will try to update OpenVino

**Comment by PINTO0309** [comment]
Close for lack of progress.
