### ISSUE TITLE
matlabは対応していますか

### ISSUE THREAD

**Issue by yudai1102jp** [PINTO0309/openvino2tensorflow#40]
matlab2020で作成したonnx形式モデルをtensorflow lite形式に変換したいと考えています。

このツールではmatlabから生成したonnxをopenvinoで変換したファイルは対応していますか？

**Comment by PINTO0309** [comment]
When converted to onnx, it is a common format. It does not matter if the tool used to generate the model is matlab or not.

**Comment by PINTO0309** [comment]
Since there seems to be no progress, I'll close it.

**Comment by yudai1102jp** [comment]
Thank you
