### ISSUE TITLE
Openvino Yolov5 list index out of range

### ISSUE THREAD

**Issue by BernardinD** [PINTO0309/openvino2tensorflow#41]
#### 9. Download URL for ONNX model
https://drive.google.com/file/d/1RSbxNDlCDiaJLCKy_iyg19MOC6W7MIza/view?usp=sharing
#### 10. Download URL for OpenVINO IR (.bin/.xml) model
https://drive.google.com/drive/folders/1Jy4_4wbwJXTNk-Lv1AYFSrN8mh8dWDUE?usp=sharing
#### 11. URL of the repository from which the transformed model was taken
https://github.com/ultralytics/yolov5

#### 13. Issue Details
We're trying to convert and customize a Yolov5 model in Keras since the EdgeTPU has issues with the 5DTranpose operation at the end and the openvino2tensorflow has issues with which dimensions to tranpose between the Openvino graph and Tensorflow. 

The idea is to use openvino2tensorflow to get a Keras and then customize the output of that conversion but we get the `index out of range` error when attempting to load the Keras model

Any suggestions on how to workaround this workaround?

**Update:** I just found out an error is throw when saving the yolo TF/Keras model. 
`Can't pickle module objects`

**Comment by PINTO0309** [comment]
The README has been substantially updated to describe how to replace weights and fixed parameters. This is a feature that was implemented six months ago to support 5DTranspose.
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op
