### ISSUE TITLE
Raspberry Pi 3B+ 

### ISSUE THREAD

**Issue by abel-kun** [PINTO0309/openvino2tensorflow#42]
![Capture](https://user-images.githubusercontent.com/60181466/125837249-18c304b0-d145-4dce-aec5-1fd5a063f233.PNG)
I am very new to linux OS please help.
I followed your steps to install Tensorflow on my RPi 3B+ but got this,
bash: ./tensorflow-2.5.0-cp37-none-linux_armv7l_download.sh: Permission denied

**Comment by PINTO0309** [comment]
Run chmod.

**Comment by abel-kun** [comment]
> Run chmod.

It says no such file or directory .
Btw great to see getting reply within minutes. Thanks!
![IMG_20210716_000207.jpg](https://user-images.githubusercontent.com/60181466/125839364-a36e456c-c909-462e-a494-f656f4ab677d.jpg)

**Comment by PINTO0309** [comment]
Why don't you specify the 2.5.0 file?

**Comment by PINTO0309** [comment]
In the first place, what you are trying to do has absolutely nothing to do with this repository. Publish the issue in the appropriate place.

**Comment by abel-kun** [comment]
Thanks anyways! 🙏
