### ISSUE TITLE
Onnx to OpenVino .. cant find the mo.py file 

### ISSUE THREAD

**Issue by letdivedeep** [PINTO0309/openvino2tensorflow#45]
hi @khursani8 @PINTO0309 

I was following the [blog](https://qiita.com/PINTO/items/ed06e03eb5c007c2e102#6-8-onnx---openvino-ir-conversion)

I have used the docker setup provided on the repo 
```
$ docker pull pinto0309/openvino2tensorflow
or
$ docker build -t pinto0309/openvino2tensorflow:latest .

# If you don't need to access the GUI of the HostPC and the USB camera.
$ docker run -it --rm \
  -v `pwd`:/home/user/workdir \
  pinto0309/openvino2tensorflow:latest
```

when I want to convert the onnx model to openvino, I am not able to get the installation dir of openvino to be input here in the {INTEL_OPENVINO_DIR} path
```
$ python3 ${INTEL_OPENVINO_DIR}/deployment_tools/model_optimizer/mo.py \
  --input_model u2netp_320x320_opt.onnx \
  --input_shape [1,3,320,320] \
  --output_dir openvino/320x320/FP32 \
  --data_type FP32
```
Does the docker comes with openvino setup .. if so what path should be inputed

**Comment by kuang-wei** [comment]
Yes it does, it's under `/opt/intel/openvino_2021`

**Comment by PINTO0309** [comment]
![Screenshot 2021-07-23 00:35:38](https://user-images.githubusercontent.com/33194443/126666928-a543c99c-2414-4f45-9acf-fca25587b309.png)

**Comment by letdivedeep** [comment]
@PINTO0309 @kuang-wei  thanks for the reply I was able to create an openvino model 

But while running this cmd 
```
openvino2tensorflow \
  --model_path openvino/mbv2_opt.xml \
  --model_output_path saved_model \
  --output_saved_model \
  --output_integer_quant_tflite \
  --output_full_integer_quant_tflite\
 --output_integer_quant_type uint8 \
 --output_tftrt \
 --output_edgetpu \
  --output_float16_quant_tflite
```
i am getting an error in the saving the saved model 
`ERROR: Message tensorflow.SavedModel exceeds maximum protobuf size of 2GB: 2763310261`

attached the snapshot below
![Screenshot 2021-07-23 at 12 25 30 PM](https://user-images.githubusercontent.com/74127861/126747277-fb662114-0c76-48bd-9a14-09d38b4778f9.png)

**Comment by PINTO0309** [comment]
Unfortunately, files that are larger than 2 GB in size after conversion cannot be converted. This is not a limitation of openvino2tensorflow, but of a file format called Protocol Buffers developed by Google.
