### ISSUE TITLE
openvino to tflite ValueError

### ISSUE THREAD

**Issue by lucci17** [PINTO0309/openvino2tensorflow#5]
I follow the [procedure](https://qiita.com/PINTO/items/ed06e03eb5c007c2e102#6-1-installing-tensorflow-and-openvino),but fail at the last step. I get the ValueError: 'F.sigmoid(d0)' is not a valid scope name.
Here is part of my pip list:
onnx                          1.8.0
onnx-simplifier               0.2.19
onnxoptimizer                 0.1.1
onnxruntime                   1.5.2
openvino-python               2021.1
openvino2tensorflow           0.4.7
tensorflow                    2.3.1
torch                         1.7.0+cu101
torchaudio                    0.7.0
torchvision                   0.8.1+cu101
I git clone openvino and open_model_zoo from the openvino github and use open_model_zoo/tools/downloader/pytorch_to_onnx.py, openvino/model-optimizer/mo.py in master branch. I get a different output u2netp_320x320_opt.xml but not u2netp_320x320.xml in step 6.8. How to  solve the ValueError? Also, I will try to convert more openvino model.

**Comment by PINTO0309** [comment]
There is no need to clone the OpenVINO or open_model_zoo repositories. Just follow the official tutorial to install OpenVINO.

You can also optimize your model with onnx-simplefier and name it u2netp_320x320_opt.onnx.

I don't know what the problem is because the error messages are not all written.

**Comment by PINTO0309** [comment]
Close for lack of progress.

**Comment by PINTO0309** [comment]
Close for lack of progress.
