### ISSUE TITLE
reshape issue

### ISSUE THREAD

**Issue by xiaomingnio** [PINTO0309/openvino2tensorflow#57]
#### 2.openvino model to convert:
https://drive.google.com/drive/folders/1I0XLgaswb-4NV_RB1MN9PyjbO3nxbhbn?usp=sharing
#### 3. Issue Details
![image](https://user-images.githubusercontent.com/25093691/128281060-f14d6316-f251-44d6-b6b7-adf9d98bbde2.png)

**Comment by PINTO0309** [comment]
Fix
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-just-beforeafter-the-operation-specified-by-layer_id
