### ISSUE TITLE
can not convert some model

### ISSUE THREAD

**Issue by vijayky88** [PINTO0309/openvino2tensorflow#6]
hi ,

i wanted to convert https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/face-reidentification-retail-0095/FP32/
but getting failed with below message:
openvino2tensorflow --model_path=openvino/448x448/FP32/Resnet34_3inputs_448x448_20200609.xml --output_saved_model True  --output_pb True --output_weight_quant_tflite True --output_float16_quant_tflite True --output_no_quant_float32_tflite True

openvino2tensorflow --model_path=FP32/face-reidentification-retail-0095.xml --output_saved_model True --output_pb True --output_weight_quant_tflite True --output_float16_quant_tflite True --output_no_quant_float32_tflite True
TensorFlow/Keras model building process starts ======================================
/home/vijay/.local/lib/python3.6/site-packages/tensorflow/python/autograph/utils/testing.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
The Input layer is not yet implemented.

please let mw know if i need to do any workaorund.

Limitation from myside:
i can not used the said model in openvino 2021 version as it failed with below message saying "intel IR files is not compatible"

openvino2tensorflow --model_path=openvino/448x448/FP32/Resnet34_3inputs_448x448_20200609.xml --output_saved_model True  --output_pb True --output_weight_quant_tflite True --output_float16_quant_tflite True --output_no_quant_float32_tflite True

openvino2tensorflow --model_path=FP32/face-reidentification-retail-0095.xml --output_saved_model True --output_pb True --output_weight_quant_tflite True --output_float16_quant_tflite True --output_no_quant_float32_tflite True
TensorFlow/Keras model building process starts ======================================
/home/vijay/.local/lib/python3.6/site-packages/tensorflow/python/autograph/utils/testing.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
The Input layer is not yet implemented.

Thanks
Vijay
skpyeid ~ vijayky88

**Comment by PINTO0309** [comment]
Unfortunately, **`face-reidentification-retail-0095`** is the OpenVINO model for 2018, so it is currently unsupported.

**Comment by vijayky88** [comment]
any work around or any suggestion ? or should i wait for the upgraded version of face-reidentification-retail-0095 from intel side

**Comment by PINTO0309** [comment]
You can try this one.https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/1/face-reidentification-retail-0095/


     ----- Original Message -----

**Comment by PINTO0309** [comment]
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/33194443/102609729-59e09d80-416f-11eb-8cb0-d74142175015.gif)

**Comment by semihstp** [comment]
Hi! I'm trying to convert my custom yolov4.weights file to tflite. 
Yolov4.weights   ->  openvino(.bin, .xml)   ->  tflite.
But i have the same issue.

The RegionYolo layer is not yet implemented.

Can @PINTO0309 help me with my problem? It's relevant my graduate project. So 
if you help me with my problem I would be very pleased.

**Comment by PINTO0309** [comment]
@semihstp 
Please issue another issue.
