### ISSUE TITLE
Input and Output shape change after conversion to Tflite from OpenVINO

### ISSUE THREAD

**Issue by letdivedeep** [PINTO0309/openvino2tensorflow#60]
Hi @PINTO0309 

I have an onnx model which i need to convert to edge TPU. My onnx model takes the input as [1,3,288,352 ] as seen below 
<img width="478" alt="onnx_in" src="https://user-images.githubusercontent.com/74127861/128870932-fcfc9172-b7d9-42bc-90ac-f917ec30ddca.png">

And the output of ONNX as [1x101x56x4]
<img width="446" alt="onnx_out" src="https://user-images.githubusercontent.com/74127861/128870963-4b2d3190-7fc6-4190-a753-c6752f0cdd72.png">

When i convert the model to open vino i use this cmd 
```
python /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
  --input_model model.onnx \
  --input_shape [1,3,288,352] \
  --output_dir openvino \
  --data_type FP32
```
And then convert the openviono to edge tpu using this cmd
```
openvino2tensorflow \
  --model_path openvino/model.xml \
  --model_output_path saved_model \
  --output_saved_model \
  --output_h5 \
  --output_pb \
  --output_no_quant_float32_tflite \
--output_edgetpu \
  --output_weight_quant_tflite \
  --output_full_integer_quant_tflite \
 --output_integer_quant_type uint8 \
--output_onnx \
 --onnx_opset 11 \
--output_tftrt \
--output_integer_quant_tflite
```

I got this change in the tflite files, where the input and output shape is changed 
Input change 
<img width="465" alt="in" src="https://user-images.githubusercontent.com/74127861/128871744-dd808779-8291-4d10-9431-3ab284f6c29c.png">

Output change
<img width="466" alt="out" src="https://user-images.githubusercontent.com/74127861/128871751-6f65e71c-3997-4033-923b-6eaa32c1dce6.png">

Can you point me to reason why its changing the shape ?

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op
If you want an accurate response, please provide a model.

**Comment by letdivedeep** [comment]
@PINTO0309  Thanks for the reply

I have attached the model in this gdrive [link](https://drive.google.com/drive/folders/1XZ25fNXh68jNkF-vg6TelEVFc7GslfdL?usp=sharing)

moreover, the results are very much hampered in the converted tflite from the openvino framework

**Comment by PINTO0309** [comment]
Since there is no progress, I'm closing it.
