### ISSUE TITLE
PriorBoxClustered layer is not yet implemented

### ISSUE THREAD

**Issue by zhongwenkun886** [PINTO0309/openvino2tensorflow#65]
I want to convert the openvino model (vehicle-detection-0201.xml) to TFlite, but when I run the converting, it show that the PriorBoxClustered layer is not yet implemented.
So How can I solve this issue?
Thanks.
vehicle-detection-0201.xml : 
https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection/model_templates/vehicle-detection

**Comment by PINTO0309** [comment]
Same issue: https://github.com/PINTO0309/openvino2tensorflow/issues/31
