### ISSUE TITLE
Problems converting person-reidentification model

### ISSUE THREAD

**Issue by eymengunay** [PINTO0309/openvino2tensorflow#7]
Hello @PINTO0309,

Recently I have stumbled upon this repo, thanks a lot for the work that you put in the project!

I have successfully converted some openvino models however it seems to fail during the conversion of "person-reidentification-retail" models. So far I have tried several different versions such as:

- person-reidentification-retail-0288
- person-reidentification-retail-0287
- person-reidentification-retail-0270
- person-reidentification-retail-0248

but unfortunately every attempt failed. Are you planning on adding support for the above mentioned reidentification models?

Thanks again!

**Comment by PINTO0309** [comment]
I am aware of the issues you have pointed out. But it is going to take some time to find a solution.

**Comment by PINTO0309** [comment]
@eymengunay 
Added support for converting "person-reidentification-retail-0248". The latest version is 1.4.5, so please update and try again.
![model_float32 tflite](https://user-images.githubusercontent.com/33194443/103183245-6b0a7680-48f4-11eb-868c-5e6c9a55445e.png)

**Comment by eymengunay** [comment]
Hello @PINTO0309,

Thanks a lot for your time and the added support. After upgrading to the latest version available I have successfully managed to convert person-reidentification-0248.
