### ISSUE TITLE
PriorBoxClustered Error while converting Vehicle-Detection-0200

### ISSUE THREAD

**Issue by HessamSH** [PINTO0309/openvino2tensorflow#70]
Thanks on the great work,
I'm trying to convert the openvino model "vehicle-detection-0200" to .pb, saved_model or h5 format but I get this error:
`The PriorBoxClustered layer is not yet implemented.`

Are there any plans to support this layer in the future as well?

**Comment by PINTO0309** [comment]
same issue: https://github.com/PINTO0309/openvino2tensorflow/issues/31
