### ISSUE TITLE
Yolov5 with Shuffle_Block model conversion error, ValueError: Dimension size must be evenly divisible by 3 but is 16

### ISSUE THREAD

**Issue by AlexisPapaioannou** [PINTO0309/openvino2tensorflow#77]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc
Windows 10
#### 3. Version of OpenVINO e.g. 2021.2.185, etc
openvino2tensorflow v1.24.8
#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc
TensorFlow  2.6.0

#### 8. Version of ONNX e.g. v1.8.0, etc
ONNX 1.8.0
#### 11. URL of the repository from which the transformed model was taken
https://github.com/ppogg/YOLOv5-Lite/blob/master/models/v5Lite-s.yaml

> layer_type: Sigmoid
layer_id: 311
input_layer0: layer_id=310: Tensor("Transpose_7:0", shape=(1, 3, 16, 16, 6), dtype=float32)
tf_layers_dict: Tensor("Sigmoid_33:0", shape=(1, 3, 16, 16, 6), dtype=float32)
====================================================================================
layer_type: Const
layer_id: 312
tf_layers_dict: (1,)
====================================================================================
layer_type: Const
layer_id: 313
tf_layers_dict: (3,)
====================================================================================
ERROR: Dimension size must be evenly divisible by 3 but is 16
	Number of ways to split should evenly divide the split dimension for '{{node lambda_6/Split}} = Split[T=DT_FLOAT, num_split=3](lambda_6/Split/split_dim, Sigmoid_33)' with input shapes: [], [1,3,16,16,6] and with computed input tensors: input[0] = <3>.
ERROR: model_path  : /content/drive/MyDrive/yolov5_greyscale_new_version/runs/train/exp/weights/optimizations/best_opt.xml
ERROR: weights_path: /content/drive/MyDrive/yolov5_greyscale_new_version/runs/train/exp/weights/optimizations/best_opt.bin
ERROR: layer_id    : 314
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1812, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 3 but is 16
	Number of ways to split should evenly divide the split dimension for '{{node lambda_6/Split}} = Split[T=DT_FLOAT, num_split=3](lambda_6/Split/split_dim, Sigmoid_33)' with input shapes: [], [1,3,16,16,6] and with computed input tensors: input[0] = <3>.

#### 13. Issue Details
I tried to convert a yolov5 model with shuffleNet, but I received the above error. Is there any solution? Also, I tried to implemented the solution from https://github.com/PINTO0309/openvino2tensorflow/issues/38 but the problem didn't solve it.

**Comment by PINTO0309** [comment]
Please provide the .xml and .bin. Otherwise, I will not respond at all.

**Comment by AlexisPapaioannou** [comment]
*Here you can find the xml file: https://drive.google.com/file/d/1fbarCM7jWa1Gioqj-d-iNqsDjHv1Tl3C/view?usp=sharing

*the .bin file: https://drive.google.com/file/d/1zj3OiInSmHrIPf--5deverxQn4MUd_vd/view?usp=sharing

*the .onnx file: https://drive.google.com/file/d/1yzxj0GjErLk7poqGivex6_69Yp07O11D/view?usp=sharing

Thanks a lot!

**Comment by AlexisPapaioannou** [comment]
And here is the new error

![error](https://user-images.githubusercontent.com/48021731/141765819-1c8b1f0d-8df7-46b7-80d5-7e426a472f7d.PNG)

**Comment by PINTO0309** [comment]
Has this model been trained by MS-COCO? Or is it your own data set?

**Comment by AlexisPapaioannou** [comment]
With my custom dataset

**Comment by PINTO0309** [comment]
I don't normally respond to individual requirements as it is not helpful to other engineers, but I will reply just in case. Next time I will not respond to individual requirements. Also, please try to at least read the README and do what you can before posting your question.

- **6-7. Replace weights or constant values in Const OP, and add Transpose or Reshape or Cast just before/after the operation specified by layer_id**
**https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-just-beforeafter-the-operation-specified-by-layer_id**

The tflite generated by the following procedure has not been tested at all. This is because it is trained on a proprietary data set. I don't know the label.

Due to the large number of 5D transposes, if the inferred results are not correct, you can adjust the JSON yourself.

- replace.json
```json
{
    "format_version": 2,
    "layers": [
        {
            "layer_id": "269",
            "type": "Const",
            "replace_mode": "direct",
            "values": [
                0,
                1,
                2,
                4,
                3
            ]
        },
        {
            "layer_id": "279",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "292",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "335",
            "type": "Const",
            "replace_mode": "direct",
            "values": [
                0,
                1,
                2,
                4,
                3
            ]
        },
        {
            "layer_id": "345",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "358",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "401",
            "type": "Const",
            "replace_mode": "direct",
            "values": [
                0,
                1,
                2,
                4,
                3
            ]
        },
        {
            "layer_id": "411",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "424",
            "type": "Transpose",
            "replace_mode": "insert_after",
            "values": [
                0,
                2,
                3,
                4,
                1
            ]
        },
        {
            "layer_id": "294",
            "type": "Concat",
            "replace_mode": "change_axis",
            "values": 3
        },
        {
            "layer_id": "296",
            "type": "Transpose",
            "replace_mode": "insert_before",
            "values": [
                0,
                4,
                1,
                2,
                3
            ]
        },
        {
            "layer_id": "360",
            "type": "Concat",
            "replace_mode": "change_axis",
            "values": 3
        },
        {
            "layer_id": "362",
            "type": "Transpose",
            "replace_mode": "insert_before",
            "values": [
                0,
                4,
                1,
                2,
                3
            ]
        },
        {
            "layer_id": "426",
            "type": "Concat",
            "replace_mode": "change_axis",
            "values": 3
        },
        {
            "layer_id": "428",
            "type": "Transpose",
            "replace_mode": "insert_before",
            "values": [
                0,
                4,
                1,
                2,
                3
            ]
        }
    ]
}
```
- script
```bash
xhost +local: && \
docker run --gpus all -it --rm \
-v `pwd`:/home/user/workdir \
-v /tmp/.X11-unix/:/tmp/.X11-unix:rw \
--device /dev/video0:/dev/video0:mwr \
--net=host \
-e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
-e DISPLAY=$DISPLAY \
--privileged \
ghcr.io/pinto0309/openvino2tensorflow:latest

# 1,3,16,16,6 N,C,D,H,W
# 1,16,16,6,3 N,D,H,W,C

openvino2tensorflow \
--model_path best_opt.xml \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--weight_replacement_config replace.json
```

**Comment by AlexisPapaioannou** [comment]
Thank you very much, I appreciate it! And one more question, is it possible by adding 3 Reshape layers before the 3 last Concatenation layers to change the 5d to 4d removing the first dimension? As the tflite which I use supports only Concatenation with max 4d.

**Comment by PINTO0309** [comment]
The 5D Concat does not exist anywhere, so I do not understand what you are saying.

**Comment by PINTO0309** [comment]
I would insert **`Reshape`** before **`Split`**.

**Comment by AlexisPapaioannou** [comment]
Okay, thanks!
