### ISSUE TITLE
ir_weight_extractor.py overwrites destination

### ISSUE THREAD

**Issue by HessamSH** [PINTO0309/openvino2tensorflow#78]
####  Ubuntu 18
I'm using the latest relese **v1.25.1** and it seems there is a fatal issue with ir_weight_extractor.py which removes the whole directory given to it as ***--output_path*** argument. I gave my ~/Desktop as the output directory and the whole Desktop content was deleted and replaced by weights. Unfortunately I wasn't to recover some of the data. I hope this issue would be fixed.

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/openvino2tensorflow/releases/tag/v1.25.2
