### ISSUE TITLE
Trouble converting  vehicle-detection-0200

### ISSUE THREAD

**Issue by HessamSH** [PINTO0309/openvino2tensorflow#79]
I'm converting the openvino *vehicle-detection-0200* model. Though the last **DetectionOutput** layer is not implemented. I changed the xml to this:

I removed the last two layers of the original model and didn't change the .bin weight file. I give the new xml to **openvino2tensorflow.py** and it runs with no errors. Though the model it gives me only has the input layer and is less than 100kb.
Did I do something wrong?
[cp.txt](https://github.com/PINTO0309/openvino2tensorflow/files/7554935/cp.txt)

**Comment by PINTO0309** [comment]
Perhaps you are editing it wrong. I can't read anything that looks like the xml file you posted, but I guess you just haven't reconnected the Result layer.

**Comment by HessamSH** [comment]
I replaced the xml text with txt file you can view.

**Comment by PINTO0309** [comment]
There is no Result layer.
![Screenshot 2021-11-17 22:34:56](https://user-images.githubusercontent.com/33194443/142210550-63911c9a-825d-4b54-a9b2-7dc697b86c7e.png)
![Screenshot 2021-11-17 22:35:07](https://user-images.githubusercontent.com/33194443/142210555-3a1a7404-65f5-4818-a80d-10687d315a09.png)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/178_vehicle-detection-0200

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/openvino2tensorflow/releases/tag/v1.25.3
https://github.com/PINTO0309/openvino2tensorflow/releases/tag/v1.25.4

**Comment by HessamSH** [comment]
> https://github.com/PINTO0309/PINTO_model_zoo/tree/main/178_vehicle-detection-0200

Thanks for the effort. Though it seems that the saved_model format you have provided has some problems. It's in the ''_UserObject' object' format and normal functions like predict and summary cannot be applied to it.

**Comment by PINTO0309** [comment]
```
>>> import tensorflow as tf
>>> import numpy as np
>>> loaded = tf.saved_model.load('saved_model_256x256')
>>> infer = loaded.signatures["serving_default"]
>>> infer(image=np.ones((1,256,256,3),dtype=np.float32))
2021-11-20 21:36:29.388833: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8200
{'tf.identity': <tf.Tensor: shape=(1, 5376), dtype=float32, numpy=
array([[-0.6882432 , -0.92401135,  0.3261156 , ..., -0.20971192,
        -0.18629664, -0.2545644 ]], dtype=float32)>, 'tf.identity_1': <tf.Tensor: shape=(1, 2688), dtype=float32, numpy=
array([[3.9097137e-04, 9.9960905e-01, 8.8063441e-04, ..., 9.9621165e-01,
        3.4444174e-03, 9.9655557e-01]], dtype=float32)>}
```

**Comment by HessamSH** [comment]
> Method name is: tensorflow/serving/predict

Thanks. Why doesn't this saved_model not have ordinary attributes of a tensorflow model? Things like summary, train, compile...
Is there a workaround for retraining this model?

**Comment by HessamSH** [comment]
I fixed the problem by converting the model to h5. It seems to be okay.

**Comment by HessamSH** [comment]
Is the DetectionOutput layer going to be implemented anytime soon?
The current workaround puts considerable calculations on CPU.

Thanks
@PINTO0309
