### ISSUE TITLE
Yolov5-Lite with shuffle block convert to tflie

### ISSUE THREAD

**Issue by ppogg** [PINTO0309/openvino2tensorflow#82]
Unbelievable, this warehouse is really great！！！

**Comment by PINTO0309** [comment]
I will not respond unless you provide ONNX or OpenVINO IR. I really dislike sloppy issues.

#77 "Yolov5 with Shuffle_Block model conversion error, ValueError: Dimension size must be evenly divisible by 3 but is 16"

**Comment by ppogg** [comment]
sorry sir，like this：
v5lite-s.xml: [https://drive.google.com/file/d/1POkWJaGG8qyebf1PCVWp_fMTmFJ4jl1C/view?usp=sharing](https://drive.google.com/file/d/1POkWJaGG8qyebf1PCVWp_fMTmFJ4jl1C/view?usp=sharing)
v5lte-s.bin: [https://drive.google.com/file/d/1Mq8cFc2rTX1KwFeaSc3bUlVyga1bWl5H/view?usp=sharing](https://drive.google.com/file/d/1Mq8cFc2rTX1KwFeaSc3bUlVyga1bWl5H/view?usp=sharing)
The dataset is coco

**Comment by PINTO0309** [comment]
There seems to be no post-processing at all, are you sure this is the complete model?
![Screenshot 2021-11-20 12:11:19](https://user-images.githubusercontent.com/33194443/142712581-4ddb5e94-eb41-48da-b337-91664aac459a.png)

**Comment by PINTO0309** [comment]
Can be converted normally.
- **`v5lite-s.tflite`**
![aaa](https://user-images.githubusercontent.com/33194443/142712920-0fedbe54-9a96-44cb-9d5e-1c54acc29d88.png)

**Comment by ppogg** [comment]
My God, can you provide a converted model? I want to see the difference with my tflite after converting.

**Comment by PINTO0309** [comment]
[saved_model.zip](https://github.com/PINTO0309/openvino2tensorflow/files/7573864/saved_model.zip)

**Comment by ppogg** [comment]
Thankyou sir. By the way, I watched this warehouse for a long time last night. It was really practical.

**Comment by PINTO0309** [comment]
Thank you. If models with post-processing are provided, I will convert them all and share them with my model zoo.
https://github.com/PINTO0309/PINTO_model_zoo

**Comment by ppogg** [comment]
Of course sir, this is my honor，like this：
![image](https://user-images.githubusercontent.com/82716366/142713994-eaf5831e-2ff8-45c7-8a2e-4829f80272a5.png)
This IR model includes post-processing：
[https://drive.google.com/file/d/1zvhzWmS_8tQEJPRLWlSbehXT_wRVY45P/view?usp=sharing](https://drive.google.com/file/d/1zvhzWmS_8tQEJPRLWlSbehXT_wRVY45P/view?usp=sharing)
![image](https://user-images.githubusercontent.com/82716366/142714181-44aef8f3-3fcb-4889-9546-58fa3b236180.png)

**Comment by ppogg** [comment]
By the way, the model you just converted for me does not work, but someone used this repo to convert yolov5 before and work: [https://github.com/lp6m/yolov5s_android/tree/master/convert_model](https://github.com/lp6m/yolov5s_android/tree/master/convert_model).
you converted for me:
![image](https://user-images.githubusercontent.com/82716366/142714327-dd2bfd12-cfc0-4049-8604-70ac8c96a451.png)
before:
![image](https://user-images.githubusercontent.com/82716366/142714416-5b65cdbc-4c85-4df1-9b75-118b48254771.png)
I use the same detect.py.
May be is a new problem, thankyou sir~

**Comment by PINTO0309** [comment]
- OpenVINO to TensorFlow to ONNX and TFLite, Comparison of inference results.
```bash
user@ubuntu2004:~/workdir$ python3 onnx_tflite_test.py 
ONNX output @@@@@@@@@@@@@@@@@@@@@@@
elapsed time: 29.294729232788086ms
shape: (1, 25200, 85)
[array([[[2.51785994e+00, 2.60093212e+00, 1.49863968e+01, ...,
         4.47389483e-03, 1.61233544e-03, 1.08805299e-02],
        [1.17213287e+01, 3.59181929e+00, 2.65871239e+01, ...,
         3.91250849e-03, 1.57558918e-03, 1.05172098e-02],
        [1.90585785e+01, 3.66961241e+00, 3.22659492e+01, ...,
         3.77982855e-03, 1.24087930e-03, 1.00672245e-02],
        ...,
        [5.61473145e+02, 6.06712646e+02, 1.61073944e+02, ...,
         7.55631924e-03, 7.73429871e-04, 1.77630782e-03],
        [5.85584778e+02, 6.07984070e+02, 1.28446884e+02, ...,
         7.52204657e-03, 8.94069672e-04, 2.54270434e-03],
        [6.17867249e+02, 6.16864014e+02, 1.56085968e+02, ...,
         7.01209903e-03, 9.43809748e-04, 2.71356106e-03]]], dtype=float32)]
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

tflite output @@@@@@@@@@@@@@@@@@@@@@@
elapsed time: 54.502010345458984ms
shape: (1, 25200, 85)
array([[[2.5178699e+00, 2.6009421e+00, 1.4986400e+01, ...,
         4.4739130e-03, 1.6123326e-03, 1.0880618e-02],
        [1.1721323e+01, 3.5918303e+00, 2.6587116e+01, ...,
         3.9125220e-03, 1.5755324e-03, 1.0517325e-02],
        [1.9058573e+01, 3.6696162e+00, 3.2265942e+01, ...,
         3.7798532e-03, 1.2408829e-03, 1.0067256e-02],
        ...,
        [5.6147308e+02, 6.0671265e+02, 1.6107385e+02, ...,
         7.5563113e-03, 7.7344757e-04, 1.7763070e-03],
        [5.8558478e+02, 6.0798407e+02, 1.2844681e+02, ...,
         7.5220633e-03, 8.9407619e-04, 2.5427316e-03],
        [6.1786725e+02, 6.1686395e+02, 1.5608585e+02, ...,
         7.0121274e-03, 9.4381260e-04, 2.7135969e-03]]], dtype=float32)
```

**Comment by ppogg** [comment]
Oh, I know. May be something I get wrong. Thankyou very much！

**Comment by PINTO0309** [comment]
Commited.
- TFLite Float32, Float16, INT8, Dynamic range quantization, ONNX, TFJS, TensorRT, OpenVINO IR FP32/FP16, Myriad Inference Engin Blob, CoreML
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/180_YOLOv5-Lite

**Comment by ppogg** [comment]
I like it, good jobs sir!

**Comment by PINTO0309** [comment]
Since there seems to be no particular progress, I will close it once. This is to list the tasks that I will need to do in the future. Please post another issue when you need it.

**Comment by NTHoang99** [comment]
> sorry sir，like this： v5lite-s.xml: https://drive.google.com/file/d/1POkWJaGG8qyebf1PCVWp_fMTmFJ4jl1C/view?usp=sharing v5lte-s.bin: https://drive.google.com/file/d/1Mq8cFc2rTX1KwFeaSc3bUlVyga1bWl5H/view?usp=sharing The dataset is coco

How to get v5lite.xml from my model ?. I try to put your v5lite-lite.xml and my v5lite-lite.bin and got this error : 
![image](https://user-images.githubusercontent.com/48252530/151481511-ef7e2006-16f9-441d-b8c0-e10f609ece6c.png)
After that, i put 2 your file xml and bin, i dont get any error.  I'm wondering if I have to use my own v5-lite.xml and v5-lite.bin file to convert them but i dont know how to get v5lite.xml.

**Comment by PINTO0309** [comment]
Please ask the author himself.
https://github.com/ppogg/YOLOv5-Lite
