### ISSUE TITLE
Change the order of the results in the Result layer

### ISSUE THREAD

**Issue by AlexisPapaioannou** [PINTO0309/openvino2tensorflow#83]
Is there any way to change the order in which the results appear in the result layers? 

I have these outputs
![image](https://user-images.githubusercontent.com/48021731/142881737-512489d2-f04f-4b79-9b6e-c6fcf693fd5b.png)

As a result this tflite model 
![image](https://user-images.githubusercontent.com/48021731/142881880-e4ea4e32-59ed-431f-9317-4873c3ab8d20.png)

But I want first to appear the "Identity:0429" and then the others.

**Comment by PINTO0309** [comment]
TensorFlow's optimizer changes the output order by itself, so my program cannot control it.

1. .tflite to .json
```bash
../flatc -t --strict-json --defaults-json -o ../schema.fbs -- xxxx.tflite
```
2. JSON rewrite.
Open the JSON in the IDE, rewrite the order of the layers by hand, and save.

3. .json to .tflite
```bash
../flatc -o . -b ../schema.fbs xxxx.json
```

- Reference article (Japanese article)
[How to reverse convert a tflite with Custom Operation to JSON, replace it with standard OP, and then regenerate the tflite](https://zenn.dev/pinto0309/articles/9d316860f8d418)

**Comment by PINTO0309** [comment]
If you have solved the problem, then you should write a solution for other engineers.
