### ISSUE TITLE
Problem with StridedSlice

### ISSUE THREAD

**Issue by beekeeper23** [PINTO0309/openvino2tensorflow#84]
Hello,
I had some problems with the StridedSlice layer. I tried to slice the vector [16, 16, 6, 3] to [16, 16, 2, 3] by using as begin vector the [0, 0, 2, 0] , as end vector the [0, 0, 4, 0] and stride vector the [1, 1, 1, 1] but I received a vector with a size of [16, 2, 6, 3]. Can anyone help me?

![stride](https://user-images.githubusercontent.com/94964187/143222450-9affaa7a-a014-4690-8a11-bb38b45c50d3.PNG)

**Comment by beekeeper23** [comment]
Thanks for your comment. I tried this change but I think that the problem is on const layers.

**Comment by PINTO0309** [comment]
Please read the README carefully. You can do almost anything you want.

**Comment by PINTO0309** [comment]
Closed due to lack of progress.
