### ISSUE TITLE
ValueError while converting OSNet Model

### ISSUE THREAD

**Issue by arsenal-2004** [PINTO0309/openvino2tensorflow#9]
Hey @PINTO0309 , thank you so much for the great work. Both this and the Model Zoo have been a huge help.
I have been trying to convert an OSNet person-reid model from ONNX to an EdgeTPU version. I was able to convert the ONNX model to the OpenVINO IR, but it fails with a value error when I try to convert from the IR to a TensorFlow Saved_Model.
`ValueError: Output tensors of a Functional model must be the output of a TensorFlow Layer (thus holding past layer metadata). Found: [[[[ 1.22419130e-02 -1.56739808e-03 -3.44633125e ....`

Could you please help me out? I have attached the XML and BIN files. 
[EDIT] Added the optimized ONNX as well, in case you need to refer to it.
[OSNet_Trial_1.zip](https://github.com/PINTO0309/openvino2tensorflow/files/5781059/OSNet_Trial_1.zip)

**Comment by PINTO0309** [comment]
The conversion was successful without any errors.
![Screenshot 2021-01-07 21:24:34](https://user-images.githubusercontent.com/33194443/103892362-cd524b00-512e-11eb-888f-843d83a07f15.png)


1. What version of openvino2tensorflow did you install? This tool is updated so frequently that I am fixing bugs on a daily basis.  The latest version is v1.5.4. `sudo pip3 install openvino2tensorflow --upgrade`
2. Please let me know which conversion command you used.

**Comment by arsenal-2004** [comment]
Hey @PINTO0309 . Thanks for the prompt reply.
I am working on Google Colab, since I do not have access to a local Intel CPU (required for OpenVINO).
I am using openvino2tensorflow version 1.5.4.
The command I used is
`
!source /opt/intel/openvino_2021.2.185/bin/setupvars.sh && openvino2tensorflow \
  --model_path '/content/drive/MyDrive/Trial_1/osnet_ain_x1_0_msmt17_opt.xml' \
  --model_output_path '/content/drive/MyDrive/Trial_1/osnet_ain_x1_0_msmt17_saved_model' \
  --output_saved_model True \
  --debug
`
I need to run the source command in the same line as the openvino2tensorflow command, otherwise the OpenVINO python package is not recognised.

**Comment by PINTO0309** [comment]
Remove --debug and try running it again.

**Comment by arsenal-2004** [comment]
Oh nice :) That worked. Thank you so much.
By the way, if I may ask, I noticed that you have added some person re-id models to the Model Zoo as well. May I ask which datasets these were trained on and if you plan to add edgetpu versions as well?

Anyways, thank you very much for all your help.

**Comment by PINTO0309** [comment]
>which datasets these were trained on

If it is not mentioned in the detailed description of the model, I do not know either.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/083_Person_Reidentification/url.txt**

> if you plan to add edgetpu versions as well?

I have already converted and committed the models that can be converted to EdgeTPU. In other words, any EdgeTPU model that is not committed is a model for which EdgeTPU Compilier will return an error. If the input resolution is too large or the structure of the model is too complex, the EdgeTPU Compilier will return an error. The conditions and specifications that cause the compiler to fail are not disclosed by the manufacturer.

**Comment by arsenal-2004** [comment]
Thank you :)
