### ISSUE TITLE
vgg model is killed

### ISSUE THREAD

**Issue by hayoyo12** [PINTO0309/openvino2tensorflow#98]
### Issue Type

Bug, Feature Request, Others

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO, ONNX, TensorFlow

### Download URL for ONNX / OpenVINO IR

wget https://s3.amazonaws.com/onnx-model-zoo/vgg/vgg16/vgg16.onnx

### Convert Script

```
# load onnx model
onnx_model = onnx.load(onnx_path)

# convert from onnnx to openVINO IR
source ../openvino_env/bin/activate
mo --input_model $onnx --output_dir $save_dir
deactivate

# convert from openVINO IR to TensorFlow using openvino2tensorflow
openvino2tensorflow --model_path $input_path --model_output_path $output_path --output_saved_model

```

### Description

While converting the openVino IR file to Tensorflow using 'openvino2tensorflow', it suddenly stopped nearly at the bottom node. 
It does not return any log. 

Please check the log images:
![image](https://user-images.githubusercontent.com/56079352/162127931-d0bf495a-89d4-4fbb-b0eb-ede277141508.png)

### Relevant Log Output

```shell
70361 Killed                  openvino2tensorflow --model_path $input_path --model_output_path $output_path --output_saved_model

```

The number, where is placed at '# killed', keeps changing.

**Comment by PINTO0309** [comment]
Perhaps it is not a problem with the specifications of this tool. Is there enough RAM in your device? It seems that TensorFlow consumes 60GB of RAM in the process of generating **`saved_model`** in the backend.

I dare to suggest that you should download `VGG16` in saved_model format from the beginning.

```bash
docker run -it --rm \
-v `pwd`:/home/user/workdir \
ghcr.io/pinto0309/openvino2tensorflow:latest

wget https://s3.amazonaws.com/onnx-model-zoo/vgg/vgg16/vgg16.onnx

MODEL=vgg16
H=224
W=224

onnxsim ${MODEL}.onnx ${MODEL}_${H}x${W}.onnx

$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model ${MODEL}_${H}x${W}.onnx \
--data_type FP32 \
--output_dir ${MODEL}_${H}x${W}/openvino/FP32 \
--model_name ${MODEL}_${H}x${W}

openvino2tensorflow \
--model_path ${MODEL}_${H}x${W}/openvino/FP32/${MODEL}_${H}x${W}.xml \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--non_verbose

pb_to_saved_model \
--pb_file_path saved_model/model_float32.pb \
--inputs inputs:0 \
--outputs model/tf.math.add_15/Add:0

mv saved_model_from_pb/* saved_model
```
![image](https://user-images.githubusercontent.com/33194443/162131361-aad33ad0-fb70-4781-9c47-5a6340797587.png)
![image](https://user-images.githubusercontent.com/33194443/162131759-55362d68-a9a6-41bb-a963-664cb482466b.png)

**Comment by hayoyo12** [comment]
@PINTO0309  I will check the RAM again. Thank you!
