### ISSUE TITLE
KeyError when running openvino2tensorflow

### ISSUE THREAD

**Issue by zenetio** [PINTO0309/openvino2tensorflow#99]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO

### Download URL for ONNX / OpenVINO IR

https://drive.google.com/drive/folders/17qXTLYHrWSVZlJlYMVCL14-jMztibmF-?usp=sharing

### Convert Script

python miniconda3/envs/yo1/Scripts/openvino2tensorflow --model_path ./openvino/my2yolov5s.xml --model_output_path tflite --output_pb --output_saved_model --output_no_quant_float32_tflite

### Description

- When I run the openvino2tensorflow script using the command line above, it runs for a while until I get an error and the conversion operation is stopped. I got the same issue in both Windows, Ubuntu, and the docker provided.
Note that the log track does mention of README 6-7 but I don't have any idea about what to do. I tried to debug the script but no success. Any help should be appreciated.
The file used can be found in the shared link

https://drive.google.com/drive/folders/17qXTLYHrWSVZlJlYMVCL14-jMztibmF-?usp=sharing

- It should run with no error until the complete conversion.

### Relevant Log Output

```shell
ERROR: '172:1'
ERROR: model_path  : ./openvino/my2yolov5s.xml
ERROR: weights_path: ./openvino/my2yolov5s.bin
ERROR: layer_id    : 173
ERROR: The trace log is below.
Traceback (most recent call last):
  File "miniconda3/envs/yo1/Scripts/openvino2tensorflow", line 1715, in convert
    temp = tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 0)]
  File "miniconda3/envs/yo1/Scripts/openvino2tensorflow", line 265, in get_tf_edges_from
    before_layer_type = get_bere_layer_type(tf_edges[key][edge_index])
  File "miniconda3/envs/yo1/Scripts/openvino2tensorflow", line 234, in get_bere_layer_type
    t = type(tf_layers_dict[before_layer])
KeyError: '172:1'
ERROR: Please refer to 6-7 in the README first. https://github.com/PINTO0309/openvino2tensorflow
```

**Comment by hayoyo12** [comment]
Same problem :((

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/openvino2tensorflow/issues?q=yolov5

**Comment by hayoyo12** [comment]
@PINTO0309  why is it closed?

**Comment by PINTO0309** [comment]
Your questions have already been resolved. Please do an issue search first.

**Comment by zenetio** [comment]
I did a search in all issues and could not find one related to this keyError. Could you please point out where is the resolved solution?

**Comment by PINTO0309** [comment]
OpenVINO in opset8 is not supported.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/openvino2tensorflow/issues/100

**Comment by PINTO0309** [comment]
Note added.
![image](https://user-images.githubusercontent.com/33194443/163429029-ff6cd4c3-9de1-403b-87a7-0f13e30f77a7.png)

**Comment by zenetio** [comment]
@PINTO0309 , tks for the tip, #100. After downloading the weights v5 and creating an env using the requirements, I could succeed in the complete conversion.

**Comment by PINTO0309** [comment]
Fix: https://github.com/PINTO0309/openvino2tensorflow/commit/f719975560abedfe9beabfd371ce60e24cda043a
openvino2tensorflow v1.29.6
